export const DELIVERY_PARTNER_CONSTANTS = {
  ENDPOINTS: {
    DELIVERY_PARTNERS_BASE: 'deliveryPartners',
    PROFILE: 'getProfile',
    PARTNER_BY_ID: ':partnerId',
    STATUS: 'status',
    EARNINGS: ':period',
    DELIVERIES_HISTORY: 'history',
  },
  MESSAGES: {
    SUCCESS: {
      PROFILE_RETRIEVED: 'Partner profile retrieved successfully',
      ALL_PARTNERS_RETRIEVED: 'Successfully fetched delivery partners',
      PARTNER_FOUND: 'Successfully fetched partner',
      STATUS_UPDATED: 'Status updated successfully',
      PARTNER_DELETED: 'Partner deleted successfully',
      EARNINGS_CALCULATED: 'Earnings calculated successfully',
      DELIVERIES_RETRIEVED: 'Paginated deliveries returned',
      PARTNER_CREATED: 'Successfully created delivery partner',
      VERIFICATION_COMPLETED: 'Partner verification completed',
    },
    ERROR: {
      UNAUTHORIZED: 'Unauthorized - Invalid or missing token',
      FORBIDDEN: 'Forbidden - Requires ADMIN role',
      PARTNER_NOT_FOUND: 'Delivery partner not found',
      INVALID_STATUS: 'Invalid status provided',
      INVALID_PERIOD: 'Invalid period. Must be one of: daily, weekly, monthly, yearly',
      INVALID_PAGINATION: 'Invalid pagination parameters',
      BAD_REQUEST: 'Bad Request',
      USER_NOT_FOUND: 'User Not Found',
      DELIVERY_PARTNER_NOT_FOUND: 'Delivery Partner Not found!!!',
      FAILED_PROFILE: 'Failed to retrieve profile',
      FAILED_CREATE: 'Failed to create delivery partner',
      FAILED_VERIFICATION: 'Failed to verify partner registration',
      FAILED_ALL_PARTNERS: 'Failed to retrieve all delivery partners',
      FAILED_FIND_BY_ID: 'Failed to find delivery partner by ID',
      FAILED_FIND_BY_EMAIL: 'Failed to find delivery partner by email',
      FAILED_FIND_BY_MOBILE: 'Failed to find delivery partner by mobile number',
      FAILED_STATUS: 'Failed to find partner status',
      FAILED_UPDATE_STATUS: 'Failed to update partner status',
      FAILED_REMOVE: 'Failed to remove delivery partner',
    },
  },

  PERIODS: {
    DAILY: 'daily',
    WEEKLY: 'weekly',
    MONTHLY: 'monthly',
    YEARLY: 'yearly',
  },
  CURRENCY: {
    DEFAULT: 'INR',
  },
};