export const SUCCESS_MESSAGES = {
  MANAGER_SIGNUP: 'Manager signup successful',
  MANAGER_LOGIN: 'Manager login successful',
  MANAGER_UPDATED: 'Manager updated successfully',
  MANAGER_DELETED: 'Manager deleted successfully',
  ORDER_PROCESSED: 'Order processed successfully',
  OPERATION_SUCCESS: 'Operation completed successfully',
  EMAIL_SENT:'Email is sent suceessfully',
  COMPLAINT_STATUS_UPDATED:'Complain status is fetched',
  COMPLAINTS_FETCHED:'Complain are fetched successfully',
  COMPLAINT_CREATED:'Complain created successfully',
};
export const ERROR_MESSAGES = {
  INVALID_CREDENTIALS: 'Invalid email or password',
  MANAGER_NOT_FOUND: 'Manager not found',
  UNAUTHORIZED: 'Unauthorized access',
  INVALID_INPUT: 'Invalid input provided',
  ORDER_PROCESS_FAILED: 'Failed to process order',
    MANAGER_ALREADY_EXISTS: 'A manager with this email already exists',
    EMAIL_SEND_FAILED:'The email was unable to sent',
    ADMIN_ONLY:'Only admin can access',
    ACCESS_DENIED:'Sorry, your access request has been denied',
    COMPLAINT_NOT_FOUND:'We could not find your complain',
  ORDER_NOT_FOUND: 'Associated order not found', 
};
