export const SUCCESS_MESSAGES = {
  MANAGER_SIGNUP: 'Manager signup successful',
  MANAGER_LOGIN: 'Manager login successful',
  MANAGER_UPDATED: 'Manager updated successfully',
  MANAGER_DELETED: 'Manager deleted successfully',
  ORDER_PROCESSED: 'Order processed successfully',
  OPERATION_SUCCESS: 'Operation completed successfully',
  EMAIL_SENT:'Email is sent suceessfully',
  COMPLAINT_STATUS_UPDATED:'Complain status is fetched',
  COMPLAINTS_FETCHED:'Complain are fetched successfully',
  COMPLAINT_CREATED:'Complain created successfully',
  ORDER_CREATED:'Order created successfully',
  MANAGER_FOUND:'Manager found',
  LOGOUT_SUCCESS:'Manager has been logged out successfully',
  RESET_LINK_SENT: 'If an account with that email exists, a password reset link has been sent',
  PASSWORD_RESET_SUCCESS: 'Password has been reset successfully',
};
export const ERROR_MESSAGES = {
  INVALID_CREDENTIALS: 'Invalid email or password',
  MANAGER_NOT_FOUND: 'Manager not found',
  UNAUTHORIZED: 'Unauthorized access',
  INVALID_INPUT: 'Invalid input provided',
  RESET_PASSWORD_FAILED:'Failed to reset password',
  ORDER_PROCESS_FAILED: 'Failed to process order',
    MANAGER_ALREADY_EXISTS: 'A manager with this email already exists',
    EMAIL_SEND_FAILED:'The email was unable to sent',
    ADMIN_ONLY:'Only admin can access',
    ACCESS_DENIED:'Sorry, your access request has been denied',
    COMPLAINT_NOT_FOUND:'We could not find your complain',
  ORDER_NOT_FOUND: 'Associated order not found', 
  CART_NOT_FOUND:'Cart not found.',
  INVALID_TOKEN:'Token is invalid',
  INVALID_OR_EXPIRED_TOKEN: 'Invalid or expired password reset token',
  REQUIRED_FIELDS_EMPTY:'Token and new password are required',
  REGISTRATION_FAILED:'The manager registration failed',
  EMAIL_PASSWORD_REQUIRED:'Email and password are required'
};
